// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByaYhtOuRGdx6woM6T8JJ7MBYcEh08afE',
    appId: '1:738917724259:web:a04effcf5ac0f698d98856',
    messagingSenderId: '738917724259',
    projectId: 'first-task-iti',
    authDomain: 'first-task-iti.firebaseapp.com',
    storageBucket: 'first-task-iti.appspot.com',
    measurementId: 'G-Y8D0EJ63XP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl0KXce4k3VA96JUb9rX1bqIxh8QNNbwY',
    appId: '1:738917724259:android:5d97c664ead4bd61d98856',
    messagingSenderId: '738917724259',
    projectId: 'first-task-iti',
    storageBucket: 'first-task-iti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rD21aUPo2CWpcB_FcE--MPbdw7RJqe4',
    appId: '1:738917724259:ios:93da1c96196a909ad98856',
    messagingSenderId: '738917724259',
    projectId: 'first-task-iti',
    storageBucket: 'first-task-iti.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rD21aUPo2CWpcB_FcE--MPbdw7RJqe4',
    appId: '1:738917724259:ios:93da1c96196a909ad98856',
    messagingSenderId: '738917724259',
    projectId: 'first-task-iti',
    storageBucket: 'first-task-iti.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByaYhtOuRGdx6woM6T8JJ7MBYcEh08afE',
    appId: '1:738917724259:web:a39d1a3ff4b42bfdd98856',
    messagingSenderId: '738917724259',
    projectId: 'first-task-iti',
    authDomain: 'first-task-iti.firebaseapp.com',
    storageBucket: 'first-task-iti.appspot.com',
    measurementId: 'G-L5DW38KPJH',
  );
}
